# 这是一个基本的工作流程，可以帮助你开始操作

name: CI

# 控制动作将何时运行。在push或pull请求时触发工作流
# 事件，但只针对主分支
on:
  push:
    branches: [ myVue3.0 ]
  

# 工作流运行由一个或多个作业组成，这些作业可以按顺序或并行运行
jobs:
  # 他的工作流包含一个名为“构建”的作业。
  build:
    # 作业将在其上运行的运行器类型
    runs-on: ubuntu-latest

    # 步骤表示将作为作业的一部分执行的任务序列
    steps:
    # 签出$GITHUB_WORKSPACE下的存储库，以便您的作业可以访问它
    - uses: actions/checkout@v2
    
    # 安装node
    uses: acctions/setup-node@v1
    with:
      node-version: 12.3.1

    #使用运行器shell运行单个命令
    - name: 安装依赖
      run: npm install
    - name: 打包
      run: npm run build  
    - name: 发布阿里云
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
        # 私钥 ssh/id_rsa
         SHH_PRIVATE_KEY: ${{ serets.PRIVATE_KEY }}
        # scp参数
         ARGS: "-avzr --delete"
        # 根目录
         SOURCE: "dist"
        # 服务器ip地址
         REMOTE_HOST: "47.98.252.43" 
        # 用户
         REMOTE_USER: "root"
        # 目标地址
         TARGET: "/root/vue-in-action"